[tool.django-stubs]
django_settings_module = "pannotationsd.settings"

[tool.flit.module]
name = "."

[tool.isort]
profile = "black"
known_first_party = [
  "spatiotemporal",
  "pannotations",
  "pannotationsd",
]

[tool.mypy]
plugins = [
  "mypy_django_plugin.main",
  "mypy_drf_plugin.main",
  "pydantic.mypy",
]
